project:
  type: website
  output-dir: docs

website:
  title: "Age-Related Macular Degeneration"
  navbar:
    right:
      - text: Home
        href: index.qmd
      - text: Background
        href: background.qmd
      - text: Epidemiology
        href: epidemiology.qmd
      - text: Diagnosis & Treatment
        href: diagnosis.qmd
      - text: Prevention
        href: prevention.qmd
      - text: References
        href: References.qmd
      - icon: github
        href: https://github.com/SarBen811/gerontology
format:
  html:
    theme: 
      light: cerulean
      dark: sandstone
    css: styles.css


