project:
  type: website
  output-dir: docs

website:
  title: "Gerontology"
  navbar:
    right:
      - text: Home
        href: index.qmd
      - text: Background
        href: background.qmd
      - text: Epidemiology
        href: epidemiology.qmd
      - text: Diagnosis & Treatment
        href: diagnosis.qmd
      - text: Prevention
        href: prevention.qmd
      - icon: github
        href: https://github.com/SarBen811/gerontology
format:
  html:
    theme: 
      light: cerulean
      dark: cyborg
    css: styles.css
bibliography: references.bib


